[package]
name = "checkout-service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "checkout-service"
path = "src/main.rs"

[dependencies]
domain-core = { path = "../../shared/domain-core" }
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
validator = { workspace = true }
dotenvy = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
hmac = "0.12"
sha2 = { workspace = true }
hex = { workspace = true }
prometheus = { workspace = true }
once_cell = { workspace = true }
rdkafka = { workspace = true }
prost = { workspace = true }

[build-dependencies]
prost-build = "0.12"
